version: '3.1'
services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: souchenstudent800
        POSTGRES_DB: transcandanceChat
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: