import React, { useEffect, useState } from 'react'
import { generateQrcode } from '../utils/api'
import { verify } from 'crypto';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faDog, faQrcode, faQuran, faShield, faXmark } from '@fortawesome/free-solid-svg-icons';



export function Qrcodeform() {
  const [qrCodeData, setQRCodeData] = useState("");
  useEffect(() => {

         generateQrcode().then((res)=>{
           setQRCodeData(res.data.qrcode)
          }).catch(() => {
            console.log("Error");
          }) // Replace with your server endpoint
          
        }, []);
        
  return (
    <div className="w-[380px] h-[600px] z-30 bg-white absolute top-0 left-0 bottom-0 right-0 m-auto rounded-[20px] overflow-hidden">
      {/* <div className="h-full flex flex-col items-center  font-['Whitney_Semibold'] pt-[50px]">
      
        <h1 className="text-black font-['Whitney_Semibold']">Two-Factor Authentication</h1>
        <h2 className='text-black px-5 text-center'>Enter the verification code generated by your mobile application</h2>
        <img src={qrCodeData ? qrCodeData : ""} alt="" className=' border-solid  border-orange-800 m-auto mt-14 w-[150px] h-[150px]' />
        <div className='flex items-center justify-center'>
        <input  className="text-black" type="number" id="digitsInput" name="digitsInput" pattern="\d*" title="Please enter digits only" min="999999" max="999999" />
        <input type="button" className='bg-blue-600 px-[25px] rounded-[10px] text-black' value="verify" />
        </div> */}
      {/* </div> */}
       <div className="h-full flex flex-col items-center  font-['Whitney_Semibold'] relative">
        <div className='w-full h-[14%] '>
            <FontAwesomeIcon icon={faXmark} className='text-black text-[35px] border-2 rounded-xl px-2 absolute top-6 right-8 cursor-pointer hover:bg-[--purple-color] hover:text-white' />
          </div>
        <div className='flex justify-center items-center  h-[80%] w-full flex-col p-5 gap-8 -mt-6'>
          <div className='ml-7 mr-auto'>
            <h1 className="text-black font-['Whitney_Semibold'] text-2xl">Two-Factor Authentication</h1>
            <span className="text-black font-['Whitney_Semibold'] text-xs">Scan this QR code to authentificate your account.</span>
          </div>

          <img src={qrCodeData ? qrCodeData : ""} alt="" className=' border-solid  border-orange-800 w-[165px]' />

          <div className='w-full border-t relative'>
            <span className='absolute  -top-[15px] px-3 left-[50%] -translate-x-[50%] bg-white text-black text-lg'>Verification Code</span>
          </div>

            <input type="text" className='w-[80%] h-10 py-5 text-black text-center text-xl tracking-[5px] rounded-lg border-2 border-[--purple-color] placeholder:tracking-normal' placeholder='Enter Your Code' maxLength={6} required/>

            <hr className='w-full'/>

            <button className='w-[80%] bg-[--purple-color]  py-3 rounded-lg cursor-pointer hover:bg-[--pink-color] ease-in-out duration-300'>Verify</button>

          </div>

       </div>
    </div> 

  )
}

